name: Build and Test
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Decode environment variables
        run: echo "${{ secrets.ENV_B64 }}" | base64 -d > .env.local
      - name: Generate Drizzle schema
        if: github.ref == 'refs/heads/main'
        run: bun run db:generate
      - name: Generate e2e Drizzle schema
        run: bun run db:generate:e2e
        if: github.ref != 'refs/heads/main'
      - name: Run Drizzle migrations
        if: github.ref == 'refs/heads/main'
        run: bun run db:migrate
      - name: Run e2e migrations
        run: bun run db:migrate:e2e
        if: github.ref != 'refs/heads/main'
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: bun run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
